import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopBar() {
  return (
    <div className="w-full flex justify-between items-center px-8 py-6 z-10 relative">
      <span className="text-2xl font-bold text-[#27FEE0] tracking-tight select-none">Privy.hl</span>
      <button className="px-6 py-2 rounded-lg border-2 border-[#27FEE0] bg-transparent text-[#27FEE0] font-bold text-base transition hover:bg-[#27FEE0] hover:text-[#0B1614]">
        Connect Wallet
      </button>
    </div>
  );
}

function Footer() {
  return (
    <footer className="w-full flex items-center justify-center py-6 z-10 relative">
      <span className="text-[#27FEE0] text-sm opacity-80">© {new Date().getFullYear()} Privy.hl. All rights reserved.</span>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen flex flex-col`}
      >
        <TopBar />
        <main className="flex-1 flex flex-col">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
