import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Providers from "./providers";
import PrivyWalletButton from "./components/PrivyWalletButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function TopBar() {
  return (
    <div className="w-full flex justify-between items-center px-8 py-6 z-10 relative">
      <a href="/" className="text-2xl font-bold text-[#27FEE0] tracking-tight select-none hover:text-white transition-colors cursor-pointer">Privy.hl</a>
      
      {/* Centered Navigation */}
      <div className="flex items-center gap-4">
        <a href="/register" className="px-4 py-2 rounded-lg bg-[#0B1614]/80 border border-[#27FEE0]/40 text-white/90 hover:text-[#27FEE0] hover:border-[#27FEE0] hover:bg-[#0B1614] transition-all duration-300 font-medium text-sm">Register DAO</a>
        <a href="/dao" className="px-4 py-2 rounded-lg bg-[#0B1614]/80 border border-[#27FEE0]/40 text-white/90 hover:text-[#27FEE0] hover:border-[#27FEE0] hover:bg-[#0B1614] transition-all duration-300 font-medium text-sm">Explore DAO</a>
        <a href="/group" className="px-4 py-2 rounded-lg bg-[#0B1614]/80 border border-[#27FEE0]/40 text-white/90 hover:text-[#27FEE0] hover:border-[#27FEE0] hover:bg-[#0B1614] transition-all duration-300 font-medium text-sm">Group</a>
      </div>
      
      <PrivyWalletButton />
    </div>
  );
}

function Footer() {
  return (
    <footer className="w-full flex items-center justify-center py-6 z-10 relative">
      <span className="text-[#27FEE0] text-sm opacity-80">© {new Date().getFullYear()} Privy.hl. All rights reserved.</span>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black min-h-screen flex flex-col`}
      >
        <Providers>
          <TopBar />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
